### ISSUE TITLE
Where's Update 5.0.0???

### ISSUE THREAD

**Issue by Light08** [DFS-Servers/BugReports#2]
Title.

**Comment by Dispenz0r** [comment]
ur delaying it fag

**Comment by Dispenz0r** [comment]
gote gote gote wheres my vote plugin


gote gote gote gimme my prophunt plugin...

pls i pay 💵

**Comment by Light08** [comment]
Buy me Save The World first, then we'll talk.

**Comment by Dispenz0r** [comment]
Daga Kotowaru!

**Comment by Dispenz0r** [comment]
get back to work my goat child...
